//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWLoggerControlService.GWLoggerHealthServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gwlogger.psi.ch/", ConfigurationName="GWLoggerHealthServiceReference.HealthSoap")]
    public interface HealthSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/IsHealthy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GWLoggerControlService.GWLoggerHealthServiceReference.HealthResponse IsHealthy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/IsHealthy", ReplyAction="*")]
        System.Threading.Tasks.Task<GWLoggerControlService.GWLoggerHealthServiceReference.HealthResponse> IsHealthyAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class HealthResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isHealthyField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsHealthy {
            get {
                return this.isHealthyField;
            }
            set {
                this.isHealthyField = value;
                this.RaisePropertyChanged("IsHealthy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HealthSoapChannel : GWLoggerControlService.GWLoggerHealthServiceReference.HealthSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HealthSoapClient : System.ServiceModel.ClientBase<GWLoggerControlService.GWLoggerHealthServiceReference.HealthSoap>, GWLoggerControlService.GWLoggerHealthServiceReference.HealthSoap {
        
        public HealthSoapClient() {
        }
        
        public HealthSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HealthSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HealthSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HealthSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GWLoggerControlService.GWLoggerHealthServiceReference.HealthResponse IsHealthy() {
            return base.Channel.IsHealthy();
        }
        
        public System.Threading.Tasks.Task<GWLoggerControlService.GWLoggerHealthServiceReference.HealthResponse> IsHealthyAsync() {
            return base.Channel.IsHealthyAsync();
        }
    }
}
