//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWLogger.ServerMon {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaesarPackage", Namespace="http://server-mon.psi.ch/")]
    public enum CaesarPackage : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateGateway = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RestartGateway = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://server-mon.psi.ch/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server-mon.psi.ch/", ConfigurationName="ServerMon.CaesarApiSoap")]
    public interface CaesarApiSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://server-mon.psi.ch/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server-mon.psi.ch/StartPackage", ReplyAction="*")]
        GWLogger.ServerMon.StartPackageResponse StartPackage(GWLogger.ServerMon.StartPackageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server-mon.psi.ch/StartPackage", ReplyAction="*")]
        System.Threading.Tasks.Task<GWLogger.ServerMon.StartPackageResponse> StartPackageAsync(GWLogger.ServerMon.StartPackageRequest request);
        
        // CODEGEN: Generating message contract since element name hostname from namespace http://server-mon.psi.ch/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server-mon.psi.ch/RunEpicsDebugTest", ReplyAction="*")]
        GWLogger.ServerMon.RunEpicsDebugTestResponse RunEpicsDebugTest(GWLogger.ServerMon.RunEpicsDebugTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server-mon.psi.ch/RunEpicsDebugTest", ReplyAction="*")]
        System.Threading.Tasks.Task<GWLogger.ServerMon.RunEpicsDebugTestResponse> RunEpicsDebugTestAsync(GWLogger.ServerMon.RunEpicsDebugTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartPackageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartPackage", Namespace="http://server-mon.psi.ch/", Order=0)]
        public GWLogger.ServerMon.StartPackageRequestBody Body;
        
        public StartPackageRequest() {
        }
        
        public StartPackageRequest(GWLogger.ServerMon.StartPackageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://server-mon.psi.ch/")]
    public partial class StartPackageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hostname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public GWLogger.ServerMon.CaesarPackage package;
        
        public StartPackageRequestBody() {
        }
        
        public StartPackageRequestBody(string username, string password, string hostname, GWLogger.ServerMon.CaesarPackage package) {
            this.username = username;
            this.password = password;
            this.hostname = hostname;
            this.package = package;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartPackageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartPackageResponse", Namespace="http://server-mon.psi.ch/", Order=0)]
        public GWLogger.ServerMon.StartPackageResponseBody Body;
        
        public StartPackageResponse() {
        }
        
        public StartPackageResponse(GWLogger.ServerMon.StartPackageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://server-mon.psi.ch/")]
    public partial class StartPackageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GWLogger.ServerMon.ArrayOfString StartPackageResult;
        
        public StartPackageResponseBody() {
        }
        
        public StartPackageResponseBody(GWLogger.ServerMon.ArrayOfString StartPackageResult) {
            this.StartPackageResult = StartPackageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunEpicsDebugTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunEpicsDebugTest", Namespace="http://server-mon.psi.ch/", Order=0)]
        public GWLogger.ServerMon.RunEpicsDebugTestRequestBody Body;
        
        public RunEpicsDebugTestRequest() {
        }
        
        public RunEpicsDebugTestRequest(GWLogger.ServerMon.RunEpicsDebugTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://server-mon.psi.ch/")]
    public partial class RunEpicsDebugTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hostname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string channel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string config;
        
        public RunEpicsDebugTestRequestBody() {
        }
        
        public RunEpicsDebugTestRequestBody(string hostname, string channel, string config) {
            this.hostname = hostname;
            this.channel = channel;
            this.config = config;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunEpicsDebugTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunEpicsDebugTestResponse", Namespace="http://server-mon.psi.ch/", Order=0)]
        public GWLogger.ServerMon.RunEpicsDebugTestResponseBody Body;
        
        public RunEpicsDebugTestResponse() {
        }
        
        public RunEpicsDebugTestResponse(GWLogger.ServerMon.RunEpicsDebugTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://server-mon.psi.ch/")]
    public partial class RunEpicsDebugTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GWLogger.ServerMon.ArrayOfString RunEpicsDebugTestResult;
        
        public RunEpicsDebugTestResponseBody() {
        }
        
        public RunEpicsDebugTestResponseBody(GWLogger.ServerMon.ArrayOfString RunEpicsDebugTestResult) {
            this.RunEpicsDebugTestResult = RunEpicsDebugTestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CaesarApiSoapChannel : GWLogger.ServerMon.CaesarApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaesarApiSoapClient : System.ServiceModel.ClientBase<GWLogger.ServerMon.CaesarApiSoap>, GWLogger.ServerMon.CaesarApiSoap {
        
        public CaesarApiSoapClient() {
        }
        
        public CaesarApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaesarApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaesarApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaesarApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GWLogger.ServerMon.StartPackageResponse GWLogger.ServerMon.CaesarApiSoap.StartPackage(GWLogger.ServerMon.StartPackageRequest request) {
            return base.Channel.StartPackage(request);
        }
        
        public GWLogger.ServerMon.ArrayOfString StartPackage(string username, string password, string hostname, GWLogger.ServerMon.CaesarPackage package) {
            GWLogger.ServerMon.StartPackageRequest inValue = new GWLogger.ServerMon.StartPackageRequest();
            inValue.Body = new GWLogger.ServerMon.StartPackageRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.hostname = hostname;
            inValue.Body.package = package;
            GWLogger.ServerMon.StartPackageResponse retVal = ((GWLogger.ServerMon.CaesarApiSoap)(this)).StartPackage(inValue);
            return retVal.Body.StartPackageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLogger.ServerMon.StartPackageResponse> GWLogger.ServerMon.CaesarApiSoap.StartPackageAsync(GWLogger.ServerMon.StartPackageRequest request) {
            return base.Channel.StartPackageAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLogger.ServerMon.StartPackageResponse> StartPackageAsync(string username, string password, string hostname, GWLogger.ServerMon.CaesarPackage package) {
            GWLogger.ServerMon.StartPackageRequest inValue = new GWLogger.ServerMon.StartPackageRequest();
            inValue.Body = new GWLogger.ServerMon.StartPackageRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.hostname = hostname;
            inValue.Body.package = package;
            return ((GWLogger.ServerMon.CaesarApiSoap)(this)).StartPackageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GWLogger.ServerMon.RunEpicsDebugTestResponse GWLogger.ServerMon.CaesarApiSoap.RunEpicsDebugTest(GWLogger.ServerMon.RunEpicsDebugTestRequest request) {
            return base.Channel.RunEpicsDebugTest(request);
        }
        
        public GWLogger.ServerMon.ArrayOfString RunEpicsDebugTest(string hostname, string channel, string config) {
            GWLogger.ServerMon.RunEpicsDebugTestRequest inValue = new GWLogger.ServerMon.RunEpicsDebugTestRequest();
            inValue.Body = new GWLogger.ServerMon.RunEpicsDebugTestRequestBody();
            inValue.Body.hostname = hostname;
            inValue.Body.channel = channel;
            inValue.Body.config = config;
            GWLogger.ServerMon.RunEpicsDebugTestResponse retVal = ((GWLogger.ServerMon.CaesarApiSoap)(this)).RunEpicsDebugTest(inValue);
            return retVal.Body.RunEpicsDebugTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLogger.ServerMon.RunEpicsDebugTestResponse> GWLogger.ServerMon.CaesarApiSoap.RunEpicsDebugTestAsync(GWLogger.ServerMon.RunEpicsDebugTestRequest request) {
            return base.Channel.RunEpicsDebugTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLogger.ServerMon.RunEpicsDebugTestResponse> RunEpicsDebugTestAsync(string hostname, string channel, string config) {
            GWLogger.ServerMon.RunEpicsDebugTestRequest inValue = new GWLogger.ServerMon.RunEpicsDebugTestRequest();
            inValue.Body = new GWLogger.ServerMon.RunEpicsDebugTestRequestBody();
            inValue.Body.hostname = hostname;
            inValue.Body.channel = channel;
            inValue.Body.config = config;
            return ((GWLogger.ServerMon.CaesarApiSoap)(this)).RunEpicsDebugTestAsync(inValue);
        }
    }
}
