//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWLoggerSoap
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gwlogger.psi.ch/", ConfigurationName="GWLoggerSoap.DataAccessSoap")]
    public interface DataAccessSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetGatewaysList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetGatewaysListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetMessageTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GetMessageTypesResponse> GetMessageTypesAsync(GWLoggerSoap.GetMessageTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetGatewaySessionsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GatewaySession[]> GetGatewaySessionsListAsync(string gatewayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GatewayStats> GetStatsAsync(string gatewayName, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/CheckQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> CheckQueryAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/SearchesPerformed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.SearchesPerformedResponse> SearchesPerformedAsync(GWLoggerSoap.SearchesPerformedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/SearchesOnChannelsPerformed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.SearchesOnChannelsPerformedResponse> SearchesOnChannelsPerformedAsync(GWLoggerSoap.SearchesOnChannelsPerformedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/MostActiveClasses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.MostActiveClassesResponse> MostActiveClassesAsync(GWLoggerSoap.MostActiveClassesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/ActiveClients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.ActiveClientsResponse> ActiveClientsAsync(GWLoggerSoap.ActiveClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/ActiveServers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.ActiveServersResponse> ActiveServersAsync(GWLoggerSoap.ActiveServersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetDataFileStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.DataFileStats[]> GetDataFileStatsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetGatewayNetworks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GetGatewayNetworksResponse> GetGatewayNetworksAsync(GWLoggerSoap.GetGatewayNetworksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/EpicsCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> EpicsCheckAsync(string gatewayName, string config, string channel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/BadClientConfig", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.HostChannelCount[]> BadClientConfigAsync(string gatewayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/MostConsumingChannel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.MostConsumingChannelResponse> MostConsumingChannelAsync(GWLoggerSoap.MostConsumingChannelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetAllStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GatewayStats[]> GetAllStatsAsync(string gatewayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetGraphAnomalies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GraphAnomalyInfo[]> GetGraphAnomaliesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetGraphAnomalyPreview", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> GetGraphAnomalyPreviewAsync(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetGraphAnomaly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GraphAnomaly> GetGraphAnomalyAsync(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/DeleteGraphAnomaly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task DeleteGraphAnomalyAsync(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/JsHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> JsHashAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetShortInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GatewayShortInformation[]> GetShortInformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetGatewayInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GatewayInformation> GetGatewayInformationAsync(string gatewayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/CpuHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> CpuHistoryAsync(string gatewayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/SearchHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> SearchHistoryAsync(string gatewayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/PVsHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> PVsHistoryAsync(string gatewayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/NetworkHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> NetworkHistoryAsync(string gatewayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetHistoricData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.GatewayHistoricData> GetHistoricDataAsync(string gatewayName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/RegisterLogMessageType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task RegisterLogMessageTypeAsync(GWLoggerSoap.MessageType[] types);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/RegisterLogMessageDetailType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task RegisterLogMessageDetailTypeAsync(GWLoggerSoap.IdValue[] types);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/LogEntries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task LogEntriesAsync(GWLoggerSoap.LogEntry[] logEntries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/BinaryLogEntries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.BinaryLogEntriesResponse> BinaryLogEntriesAsync(GWLoggerSoap.BinaryLogEntriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetBufferUsage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> GetBufferUsageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetCpu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> GetCpuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/LogEntry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task LogEntryAsync(string gateway, string remoteIpPoint, int messageType, GWLoggerSoap.LogEntryDetail[] details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/UpdateLastGatewaySessionInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task UpdateLastGatewaySessionInformationAsync(string gateway, GWLoggerSoap.RestartType restartType, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gwlogger.psi.ch/GetFreeSpace", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GWLoggerSoap.FreeSpace> GetFreeSpaceAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class KeyValuePairOfInt32String
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class FreeSpace
    {
        
        private ulong totMBField;
        
        private ulong freeMBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ulong TotMB
        {
            get
            {
                return this.totMBField;
            }
            set
            {
                this.totMBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ulong FreeMB
        {
            get
            {
                return this.freeMBField;
            }
            set
            {
                this.freeMBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class LogEntryDetail
    {
        
        private int typeIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TypeId
        {
            get
            {
                return this.typeIdField;
            }
            set
            {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class LogEntry
    {
        
        private string gatewayField;
        
        private string remoteIpPointField;
        
        private int messageTypeField;
        
        private LogEntryDetail[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Gateway
        {
            get
            {
                return this.gatewayField;
            }
            set
            {
                this.gatewayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RemoteIpPoint
        {
            get
            {
                return this.remoteIpPointField;
            }
            set
            {
                this.remoteIpPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MessageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public LogEntryDetail[] Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class IdValue
    {
        
        private int idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class MessageType
    {
        
        private int idField;
        
        private string nameField;
        
        private string displayMaskField;
        
        private int logLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DisplayMask
        {
            get
            {
                return this.displayMaskField;
            }
            set
            {
                this.displayMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int LogLevel
        {
            get
            {
                return this.logLevelField;
            }
            set
            {
                this.logLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class GatewayInformation
    {
        
        private string nameField;
        
        private System.Nullable<double> cPUField;
        
        private System.Nullable<int> memField;
        
        private System.Nullable<int> searchesField;
        
        private string buildField;
        
        private string versionField;
        
        private System.Nullable<int> messagesField;
        
        private System.Nullable<int> pVsField;
        
        private string runningTimeField;
        
        private System.Nullable<int> nbClientsField;
        
        private System.Nullable<int> nbServersField;
        
        private System.Nullable<double> networkField;
        
        private System.Nullable<int> nbGetsField;
        
        private System.Nullable<int> nbPutsField;
        
        private System.Nullable<int> nbNewMonsField;
        
        private System.Nullable<int> nbMonsField;
        
        private System.Nullable<int> nbCreatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<double> CPU
        {
            get
            {
                return this.cPUField;
            }
            set
            {
                this.cPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Mem
        {
            get
            {
                return this.memField;
            }
            set
            {
                this.memField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Searches
        {
            get
            {
                return this.searchesField;
            }
            set
            {
                this.searchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Build
        {
            get
            {
                return this.buildField;
            }
            set
            {
                this.buildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> PVs
        {
            get
            {
                return this.pVsField;
            }
            set
            {
                this.pVsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RunningTime
        {
            get
            {
                return this.runningTimeField;
            }
            set
            {
                this.runningTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> NbClients
        {
            get
            {
                return this.nbClientsField;
            }
            set
            {
                this.nbClientsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> NbServers
        {
            get
            {
                return this.nbServersField;
            }
            set
            {
                this.nbServersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<double> Network
        {
            get
            {
                return this.networkField;
            }
            set
            {
                this.networkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> NbGets
        {
            get
            {
                return this.nbGetsField;
            }
            set
            {
                this.nbGetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> NbPuts
        {
            get
            {
                return this.nbPutsField;
            }
            set
            {
                this.nbPutsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> NbNewMons
        {
            get
            {
                return this.nbNewMonsField;
            }
            set
            {
                this.nbNewMonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> NbMons
        {
            get
            {
                return this.nbMonsField;
            }
            set
            {
                this.nbMonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> NbCreates
        {
            get
            {
                return this.nbCreatesField;
            }
            set
            {
                this.nbCreatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class GatewayShortInformation
    {
        
        private string nameField;
        
        private System.Nullable<double> cPUField;
        
        private System.Nullable<int> memField;
        
        private System.Nullable<int> searchesField;
        
        private string buildField;
        
        private int stateField;
        
        private string versionField;
        
        private string runningTimeField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<double> CPU
        {
            get
            {
                return this.cPUField;
            }
            set
            {
                this.cPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Mem
        {
            get
            {
                return this.memField;
            }
            set
            {
                this.memField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Searches
        {
            get
            {
                return this.searchesField;
            }
            set
            {
                this.searchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Build
        {
            get
            {
                return this.buildField;
            }
            set
            {
                this.buildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RunningTime
        {
            get
            {
                return this.runningTimeField;
            }
            set
            {
                this.runningTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class GatewayHistoricData
    {
        
        private HistoricData[] cPUField;
        
        private HistoricData[] searchesField;
        
        private HistoricData[] pVsField;
        
        private HistoricData[] networkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public HistoricData[] CPU
        {
            get
            {
                return this.cPUField;
            }
            set
            {
                this.cPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public HistoricData[] Searches
        {
            get
            {
                return this.searchesField;
            }
            set
            {
                this.searchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public HistoricData[] PVs
        {
            get
            {
                return this.pVsField;
            }
            set
            {
                this.pVsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public HistoricData[] Network
        {
            get
            {
                return this.networkField;
            }
            set
            {
                this.networkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class HistoricData
    {
        
        private double valueField;
        
        private System.DateTime dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class QueryResultValue
    {
        
        private double valueField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class InterestingEventType
    {
        
        private QueryResultValue eventTypeField;
        
        private QueryResultValue[] topRemotesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QueryResultValue EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public QueryResultValue[] TopRemotes
        {
            get
            {
                return this.topRemotesField;
            }
            set
            {
                this.topRemotesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class GraphAnomaly
    {
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private string nameField;
        
        private InterestingEventType[] interestingEventTypeRemotesField;
        
        private QueryResultValue[] beforeRemoteCountsField;
        
        private QueryResultValue[] duringRemoteCountsField;
        
        private QueryResultValue[] beforeEventTypesField;
        
        private QueryResultValue[] duringEventTypesField;
        
        private GatewayHistoricData historyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public InterestingEventType[] InterestingEventTypeRemotes
        {
            get
            {
                return this.interestingEventTypeRemotesField;
            }
            set
            {
                this.interestingEventTypeRemotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public QueryResultValue[] BeforeRemoteCounts
        {
            get
            {
                return this.beforeRemoteCountsField;
            }
            set
            {
                this.beforeRemoteCountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public QueryResultValue[] DuringRemoteCounts
        {
            get
            {
                return this.duringRemoteCountsField;
            }
            set
            {
                this.duringRemoteCountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public QueryResultValue[] BeforeEventTypes
        {
            get
            {
                return this.beforeEventTypesField;
            }
            set
            {
                this.beforeEventTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public QueryResultValue[] DuringEventTypes
        {
            get
            {
                return this.duringEventTypesField;
            }
            set
            {
                this.duringEventTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public GatewayHistoricData History
        {
            get
            {
                return this.historyField;
            }
            set
            {
                this.historyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class GraphAnomalyInfo
    {
        
        private string fileNameField;
        
        private string nameField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class HostChannelCount
    {
        
        private string hostnameField;
        
        private string channelField;
        
        private int countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Hostname
        {
            get
            {
                return this.hostnameField;
            }
            set
            {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class KeyValuePairOfStringString
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class DataFileStats
    {
        
        private double logsPerSecondsField;
        
        private long averageEntryBytesField;
        
        private string nameField;
        
        private long totalDataSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double LogsPerSeconds
        {
            get
            {
                return this.logsPerSecondsField;
            }
            set
            {
                this.logsPerSecondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long AverageEntryBytes
        {
            get
            {
                return this.averageEntryBytesField;
            }
            set
            {
                this.averageEntryBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long TotalDataSize
        {
            get
            {
                return this.totalDataSizeField;
            }
            set
            {
                this.totalDataSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class KeyValuePairOfStringInt32
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class LogStat
    {
        
        private System.DateTime dateField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class GatewayStats
    {
        
        private LogStat[] logsField;
        
        private LogStat[] searchesField;
        
        private LogStat[] errorsField;
        
        private LogStat[] cPUField;
        
        private LogStat[] pVsField;
        
        private LogStat[] clientsField;
        
        private LogStat[] serversField;
        
        private LogStat[] msgSecsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public LogStat[] Logs
        {
            get
            {
                return this.logsField;
            }
            set
            {
                this.logsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public LogStat[] Searches
        {
            get
            {
                return this.searchesField;
            }
            set
            {
                this.searchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LogStat[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public LogStat[] CPU
        {
            get
            {
                return this.cPUField;
            }
            set
            {
                this.cPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public LogStat[] PVs
        {
            get
            {
                return this.pVsField;
            }
            set
            {
                this.pVsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public LogStat[] Clients
        {
            get
            {
                return this.clientsField;
            }
            set
            {
                this.clientsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public LogStat[] Servers
        {
            get
            {
                return this.serversField;
            }
            set
            {
                this.serversField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public LogStat[] MsgSecs
        {
            get
            {
                return this.msgSecsField;
            }
            set
            {
                this.msgSecsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public partial class GatewaySession
    {
        
        private System.Nullable<System.DateTime> endDateField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private long nbEntriesField;
        
        private string descriptionField;
        
        private RestartType restartTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long NbEntries
        {
            get
            {
                return this.nbEntriesField;
            }
            set
            {
                this.nbEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public RestartType RestartType
        {
            get
            {
                return this.restartTypeField;
            }
            set
            {
                this.restartTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gwlogger.psi.ch/")]
    public enum RestartType
    {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        WatchdogNoResponse,
        
        /// <remarks/>
        WatchdogCPULimit,
        
        /// <remarks/>
        GatewayUpdate,
        
        /// <remarks/>
        ManualRestart,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageTypes", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class GetMessageTypesRequest
    {
        
        public GetMessageTypesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageTypesResponse", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class GetMessageTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GWLoggerSoap.KeyValuePairOfInt32String[] GetMessageTypesResult;
        
        public GetMessageTypesResponse()
        {
        }
        
        public GetMessageTypesResponse(GWLoggerSoap.KeyValuePairOfInt32String[] GetMessageTypesResult)
        {
            this.GetMessageTypesResult = GetMessageTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchesPerformed", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class SearchesPerformedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        public string gatewayName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=1)]
        public System.DateTime datePoint;
        
        public SearchesPerformedRequest()
        {
        }
        
        public SearchesPerformedRequest(string gatewayName, System.DateTime datePoint)
        {
            this.gatewayName = gatewayName;
            this.datePoint = datePoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchesPerformedResponse", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class SearchesPerformedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GWLoggerSoap.KeyValuePairOfStringInt32[] SearchesPerformedResult;
        
        public SearchesPerformedResponse()
        {
        }
        
        public SearchesPerformedResponse(GWLoggerSoap.KeyValuePairOfStringInt32[] SearchesPerformedResult)
        {
            this.SearchesPerformedResult = SearchesPerformedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchesOnChannelsPerformed", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class SearchesOnChannelsPerformedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        public string gatewayName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=1)]
        public System.DateTime datePoint;
        
        public SearchesOnChannelsPerformedRequest()
        {
        }
        
        public SearchesOnChannelsPerformedRequest(string gatewayName, System.DateTime datePoint)
        {
            this.gatewayName = gatewayName;
            this.datePoint = datePoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchesOnChannelsPerformedResponse", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class SearchesOnChannelsPerformedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GWLoggerSoap.KeyValuePairOfStringInt32[] SearchesOnChannelsPerformedResult;
        
        public SearchesOnChannelsPerformedResponse()
        {
        }
        
        public SearchesOnChannelsPerformedResponse(GWLoggerSoap.KeyValuePairOfStringInt32[] SearchesOnChannelsPerformedResult)
        {
            this.SearchesOnChannelsPerformedResult = SearchesOnChannelsPerformedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MostActiveClasses", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class MostActiveClassesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        public string gatewayName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=1)]
        public System.DateTime datePoint;
        
        public MostActiveClassesRequest()
        {
        }
        
        public MostActiveClassesRequest(string gatewayName, System.DateTime datePoint)
        {
            this.gatewayName = gatewayName;
            this.datePoint = datePoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MostActiveClassesResponse", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class MostActiveClassesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GWLoggerSoap.KeyValuePairOfStringInt32[] MostActiveClassesResult;
        
        public MostActiveClassesResponse()
        {
        }
        
        public MostActiveClassesResponse(GWLoggerSoap.KeyValuePairOfStringInt32[] MostActiveClassesResult)
        {
            this.MostActiveClassesResult = MostActiveClassesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActiveClients", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class ActiveClientsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        public string gatewayName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=1)]
        public System.DateTime datePoint;
        
        public ActiveClientsRequest()
        {
        }
        
        public ActiveClientsRequest(string gatewayName, System.DateTime datePoint)
        {
            this.gatewayName = gatewayName;
            this.datePoint = datePoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActiveClientsResponse", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class ActiveClientsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GWLoggerSoap.KeyValuePairOfStringInt32[] ActiveClientsResult;
        
        public ActiveClientsResponse()
        {
        }
        
        public ActiveClientsResponse(GWLoggerSoap.KeyValuePairOfStringInt32[] ActiveClientsResult)
        {
            this.ActiveClientsResult = ActiveClientsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActiveServers", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class ActiveServersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        public string gatewayName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=1)]
        public System.DateTime datePoint;
        
        public ActiveServersRequest()
        {
        }
        
        public ActiveServersRequest(string gatewayName, System.DateTime datePoint)
        {
            this.gatewayName = gatewayName;
            this.datePoint = datePoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActiveServersResponse", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class ActiveServersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GWLoggerSoap.KeyValuePairOfStringInt32[] ActiveServersResult;
        
        public ActiveServersResponse()
        {
        }
        
        public ActiveServersResponse(GWLoggerSoap.KeyValuePairOfStringInt32[] ActiveServersResult)
        {
            this.ActiveServersResult = ActiveServersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGatewayNetworks", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class GetGatewayNetworksRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        public string gatewayName;
        
        public GetGatewayNetworksRequest()
        {
        }
        
        public GetGatewayNetworksRequest(string gatewayName)
        {
            this.gatewayName = gatewayName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGatewayNetworksResponse", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class GetGatewayNetworksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GWLoggerSoap.KeyValuePairOfStringString[] GetGatewayNetworksResult;
        
        public GetGatewayNetworksResponse()
        {
        }
        
        public GetGatewayNetworksResponse(GWLoggerSoap.KeyValuePairOfStringString[] GetGatewayNetworksResult)
        {
            this.GetGatewayNetworksResult = GetGatewayNetworksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MostConsumingChannel", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class MostConsumingChannelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        public string gatewayName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=1)]
        public System.DateTime datePoint;
        
        public MostConsumingChannelRequest()
        {
        }
        
        public MostConsumingChannelRequest(string gatewayName, System.DateTime datePoint)
        {
            this.gatewayName = gatewayName;
            this.datePoint = datePoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MostConsumingChannelResponse", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class MostConsumingChannelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GWLoggerSoap.KeyValuePairOfStringInt32[] MostConsumingChannelResult;
        
        public MostConsumingChannelResponse()
        {
        }
        
        public MostConsumingChannelResponse(GWLoggerSoap.KeyValuePairOfStringInt32[] MostConsumingChannelResult)
        {
            this.MostConsumingChannelResult = MostConsumingChannelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BinaryLogEntries", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class BinaryLogEntriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=0)]
        public string gateway;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gwlogger.psi.ch/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data;
        
        public BinaryLogEntriesRequest()
        {
        }
        
        public BinaryLogEntriesRequest(string gateway, byte[] data)
        {
            this.gateway = gateway;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BinaryLogEntriesResponse", WrapperNamespace="http://gwlogger.psi.ch/", IsWrapped=true)]
    public partial class BinaryLogEntriesResponse
    {
        
        public BinaryLogEntriesResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface DataAccessSoapChannel : GWLoggerSoap.DataAccessSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class DataAccessSoapClient : System.ServiceModel.ClientBase<GWLoggerSoap.DataAccessSoap>, GWLoggerSoap.DataAccessSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataAccessSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DataAccessSoapClient.GetBindingForEndpoint(endpointConfiguration), DataAccessSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAccessSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataAccessSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAccessSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataAccessSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAccessSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string[]> GetGatewaysListAsync()
        {
            return base.Channel.GetGatewaysListAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLoggerSoap.GetMessageTypesResponse> GWLoggerSoap.DataAccessSoap.GetMessageTypesAsync(GWLoggerSoap.GetMessageTypesRequest request)
        {
            return base.Channel.GetMessageTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GetMessageTypesResponse> GetMessageTypesAsync()
        {
            GWLoggerSoap.GetMessageTypesRequest inValue = new GWLoggerSoap.GetMessageTypesRequest();
            return ((GWLoggerSoap.DataAccessSoap)(this)).GetMessageTypesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GatewaySession[]> GetGatewaySessionsListAsync(string gatewayName)
        {
            return base.Channel.GetGatewaySessionsListAsync(gatewayName);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GatewayStats> GetStatsAsync(string gatewayName, System.DateTime start, System.DateTime end)
        {
            return base.Channel.GetStatsAsync(gatewayName, start, end);
        }
        
        public System.Threading.Tasks.Task<bool> CheckQueryAsync(string query)
        {
            return base.Channel.CheckQueryAsync(query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLoggerSoap.SearchesPerformedResponse> GWLoggerSoap.DataAccessSoap.SearchesPerformedAsync(GWLoggerSoap.SearchesPerformedRequest request)
        {
            return base.Channel.SearchesPerformedAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.SearchesPerformedResponse> SearchesPerformedAsync(string gatewayName, System.DateTime datePoint)
        {
            GWLoggerSoap.SearchesPerformedRequest inValue = new GWLoggerSoap.SearchesPerformedRequest();
            inValue.gatewayName = gatewayName;
            inValue.datePoint = datePoint;
            return ((GWLoggerSoap.DataAccessSoap)(this)).SearchesPerformedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLoggerSoap.SearchesOnChannelsPerformedResponse> GWLoggerSoap.DataAccessSoap.SearchesOnChannelsPerformedAsync(GWLoggerSoap.SearchesOnChannelsPerformedRequest request)
        {
            return base.Channel.SearchesOnChannelsPerformedAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.SearchesOnChannelsPerformedResponse> SearchesOnChannelsPerformedAsync(string gatewayName, System.DateTime datePoint)
        {
            GWLoggerSoap.SearchesOnChannelsPerformedRequest inValue = new GWLoggerSoap.SearchesOnChannelsPerformedRequest();
            inValue.gatewayName = gatewayName;
            inValue.datePoint = datePoint;
            return ((GWLoggerSoap.DataAccessSoap)(this)).SearchesOnChannelsPerformedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLoggerSoap.MostActiveClassesResponse> GWLoggerSoap.DataAccessSoap.MostActiveClassesAsync(GWLoggerSoap.MostActiveClassesRequest request)
        {
            return base.Channel.MostActiveClassesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.MostActiveClassesResponse> MostActiveClassesAsync(string gatewayName, System.DateTime datePoint)
        {
            GWLoggerSoap.MostActiveClassesRequest inValue = new GWLoggerSoap.MostActiveClassesRequest();
            inValue.gatewayName = gatewayName;
            inValue.datePoint = datePoint;
            return ((GWLoggerSoap.DataAccessSoap)(this)).MostActiveClassesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLoggerSoap.ActiveClientsResponse> GWLoggerSoap.DataAccessSoap.ActiveClientsAsync(GWLoggerSoap.ActiveClientsRequest request)
        {
            return base.Channel.ActiveClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.ActiveClientsResponse> ActiveClientsAsync(string gatewayName, System.DateTime datePoint)
        {
            GWLoggerSoap.ActiveClientsRequest inValue = new GWLoggerSoap.ActiveClientsRequest();
            inValue.gatewayName = gatewayName;
            inValue.datePoint = datePoint;
            return ((GWLoggerSoap.DataAccessSoap)(this)).ActiveClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLoggerSoap.ActiveServersResponse> GWLoggerSoap.DataAccessSoap.ActiveServersAsync(GWLoggerSoap.ActiveServersRequest request)
        {
            return base.Channel.ActiveServersAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.ActiveServersResponse> ActiveServersAsync(string gatewayName, System.DateTime datePoint)
        {
            GWLoggerSoap.ActiveServersRequest inValue = new GWLoggerSoap.ActiveServersRequest();
            inValue.gatewayName = gatewayName;
            inValue.datePoint = datePoint;
            return ((GWLoggerSoap.DataAccessSoap)(this)).ActiveServersAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.DataFileStats[]> GetDataFileStatsAsync()
        {
            return base.Channel.GetDataFileStatsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLoggerSoap.GetGatewayNetworksResponse> GWLoggerSoap.DataAccessSoap.GetGatewayNetworksAsync(GWLoggerSoap.GetGatewayNetworksRequest request)
        {
            return base.Channel.GetGatewayNetworksAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GetGatewayNetworksResponse> GetGatewayNetworksAsync(string gatewayName)
        {
            GWLoggerSoap.GetGatewayNetworksRequest inValue = new GWLoggerSoap.GetGatewayNetworksRequest();
            inValue.gatewayName = gatewayName;
            return ((GWLoggerSoap.DataAccessSoap)(this)).GetGatewayNetworksAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> EpicsCheckAsync(string gatewayName, string config, string channel)
        {
            return base.Channel.EpicsCheckAsync(gatewayName, config, channel);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.HostChannelCount[]> BadClientConfigAsync(string gatewayName)
        {
            return base.Channel.BadClientConfigAsync(gatewayName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLoggerSoap.MostConsumingChannelResponse> GWLoggerSoap.DataAccessSoap.MostConsumingChannelAsync(GWLoggerSoap.MostConsumingChannelRequest request)
        {
            return base.Channel.MostConsumingChannelAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.MostConsumingChannelResponse> MostConsumingChannelAsync(string gatewayName, System.DateTime datePoint)
        {
            GWLoggerSoap.MostConsumingChannelRequest inValue = new GWLoggerSoap.MostConsumingChannelRequest();
            inValue.gatewayName = gatewayName;
            inValue.datePoint = datePoint;
            return ((GWLoggerSoap.DataAccessSoap)(this)).MostConsumingChannelAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GatewayStats[]> GetAllStatsAsync(string gatewayName)
        {
            return base.Channel.GetAllStatsAsync(gatewayName);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GraphAnomalyInfo[]> GetGraphAnomaliesAsync()
        {
            return base.Channel.GetGraphAnomaliesAsync();
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> GetGraphAnomalyPreviewAsync(string filename)
        {
            return base.Channel.GetGraphAnomalyPreviewAsync(filename);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GraphAnomaly> GetGraphAnomalyAsync(string filename)
        {
            return base.Channel.GetGraphAnomalyAsync(filename);
        }
        
        public System.Threading.Tasks.Task DeleteGraphAnomalyAsync(string filename)
        {
            return base.Channel.DeleteGraphAnomalyAsync(filename);
        }
        
        public System.Threading.Tasks.Task<string> JsHashAsync()
        {
            return base.Channel.JsHashAsync();
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GatewayShortInformation[]> GetShortInformationAsync()
        {
            return base.Channel.GetShortInformationAsync();
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GatewayInformation> GetGatewayInformationAsync(string gatewayName)
        {
            return base.Channel.GetGatewayInformationAsync(gatewayName);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> CpuHistoryAsync(string gatewayName)
        {
            return base.Channel.CpuHistoryAsync(gatewayName);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> SearchHistoryAsync(string gatewayName)
        {
            return base.Channel.SearchHistoryAsync(gatewayName);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> PVsHistoryAsync(string gatewayName)
        {
            return base.Channel.PVsHistoryAsync(gatewayName);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.HistoricData[]> NetworkHistoryAsync(string gatewayName)
        {
            return base.Channel.NetworkHistoryAsync(gatewayName);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.GatewayHistoricData> GetHistoricDataAsync(string gatewayName)
        {
            return base.Channel.GetHistoricDataAsync(gatewayName);
        }
        
        public System.Threading.Tasks.Task RegisterLogMessageTypeAsync(GWLoggerSoap.MessageType[] types)
        {
            return base.Channel.RegisterLogMessageTypeAsync(types);
        }
        
        public System.Threading.Tasks.Task RegisterLogMessageDetailTypeAsync(GWLoggerSoap.IdValue[] types)
        {
            return base.Channel.RegisterLogMessageDetailTypeAsync(types);
        }
        
        public System.Threading.Tasks.Task LogEntriesAsync(GWLoggerSoap.LogEntry[] logEntries)
        {
            return base.Channel.LogEntriesAsync(logEntries);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GWLoggerSoap.BinaryLogEntriesResponse> GWLoggerSoap.DataAccessSoap.BinaryLogEntriesAsync(GWLoggerSoap.BinaryLogEntriesRequest request)
        {
            return base.Channel.BinaryLogEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.BinaryLogEntriesResponse> BinaryLogEntriesAsync(string gateway, byte[] data)
        {
            GWLoggerSoap.BinaryLogEntriesRequest inValue = new GWLoggerSoap.BinaryLogEntriesRequest();
            inValue.gateway = gateway;
            inValue.data = data;
            return ((GWLoggerSoap.DataAccessSoap)(this)).BinaryLogEntriesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<double> GetBufferUsageAsync()
        {
            return base.Channel.GetBufferUsageAsync();
        }
        
        public System.Threading.Tasks.Task<double> GetCpuAsync()
        {
            return base.Channel.GetCpuAsync();
        }
        
        public System.Threading.Tasks.Task LogEntryAsync(string gateway, string remoteIpPoint, int messageType, GWLoggerSoap.LogEntryDetail[] details)
        {
            return base.Channel.LogEntryAsync(gateway, remoteIpPoint, messageType, details);
        }
        
        public System.Threading.Tasks.Task UpdateLastGatewaySessionInformationAsync(string gateway, GWLoggerSoap.RestartType restartType, string comment)
        {
            return base.Channel.UpdateLastGatewaySessionInformationAsync(gateway, restartType, comment);
        }
        
        public System.Threading.Tasks.Task<GWLoggerSoap.FreeSpace> GetFreeSpaceAsync()
        {
            return base.Channel.GetFreeSpaceAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataAccessSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DataAccessSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataAccessSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://caesar.psi.ch/DataAccess.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DataAccessSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://caesar.psi.ch/DataAccess.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DataAccessSoap,
            
            DataAccessSoap12,
        }
    }
}
